export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESSS= "PRODUCT_LIST_SUCCESSS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESSS= "PRODUCT_DETAIL_SUCCESSS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"